"use client";
import { useCallback, useEffect, useState } from 'react';
import { requestJson } from '@/lib/client-request';
import { todayInPeru } from '@/lib/calendar.mjs';
type Announcement={id:number;canal:string;enlace:string;fechaPublicacion:string;precioPublicado:string;precioVenta:string|null;pendiente:boolean};
const empty={canal:'',enlace:'',fechaPublicacion:'',precioPublicado:''};
export default function ExternalAnnouncements({propertyId,editable,price}:{propertyId:number;editable:boolean;price:string|null}){
 const [items,setItems]=useState<Announcement[]>([]);const [form,setForm]=useState({...empty});const [editId,setEditId]=useState<number|null>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const url=`/api/inmuebles/${propertyId}/anuncios`;
 const load=useCallback(async(signal?:AbortSignal)=>{try{const data=await requestJson<{items:Announcement[]}>(url,{signal});if(!signal?.aborted)setItems(data.items);}catch(error){if(!signal?.aborted)setError(error instanceof Error?error.message:'No se pudieron cargar los anuncios.');}finally{if(!signal?.aborted)setLoading(false);}},[url]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>load(controller.signal));return()=>controller.abort();},[load]);
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{await requestJson(url,{method:editId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,id:editId})});await load();setEditId(null);setForm({...empty});setMessage('Anuncio registrado. Confirma aquí los datos que ya actualizaste en el canal externo.');}catch(error){setError(error instanceof Error?error.message:'No se pudo guardar.');}finally{setBusy(false);}}
 return <section className="mt-5 border-t border-slate-200 pt-5"><h3 className="text-sm font-bold">Anuncios externos</h3><p className="mt-2 text-xs text-slate-600">Registra dónde se publicó y confirma las actualizaciones realizadas en cada canal.</p>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="mt-3 text-sm text-emerald-800">{message}</p>}{loading?<p className="mt-3 text-sm">Consultando anuncios…</p>:items.length?items.map(item=><article key={item.id} className="mt-3 rounded-xl border border-slate-200 p-4"><p className="text-sm font-bold">{item.canal}</p><a target="_blank" rel="noopener noreferrer" href={item.enlace} className="mt-2 inline-flex min-h-11 text-sm font-semibold text-red-700 underline">Abrir anuncio →</a><p className="text-xs text-slate-600">Fecha: {item.fechaPublicacion} · Precio publicado: S/ {Number(item.precioPublicado).toLocaleString('es-PE')}</p><p className={`mt-2 text-xs font-bold ${item.pendiente?'text-amber-800':'text-emerald-800'}`}>{item.pendiente?'Anuncio pendiente de actualizar':'Actualización confirmada'}</p>{editable&&<button type="button" className="aa-button aa-button-secondary mt-3" onClick={()=>{setEditId(item.id);setForm({canal:item.canal,enlace:item.enlace,fechaPublicacion:item.fechaPublicacion,precioPublicado:price??item.precioPublicado});}}>Revisar y confirmar actualización</button>}</article>):<p className="mt-3 text-sm text-slate-600">No hay canales registrados para este inmueble.</p>}{editable&&<details className="mt-4" open={editId!==null||undefined}><summary className="cursor-pointer text-sm font-semibold">{editId?'Actualizar anuncio seleccionado':'Registrar un canal de publicación'}</summary><form onSubmit={save} className="mt-3 space-y-3"><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2">{([['canal','Canal','text'],['enlace','Enlace del anuncio','url'],['fechaPublicacion','Fecha de publicación','date'],['precioPublicado','Precio publicado (S/)','number']] as const).map(([key,label,type])=><label key={key} className="text-xs font-semibold">{label}<input type={type} required maxLength={key==='canal'?80:key==='enlace'?1000:undefined} max={type==='date'?todayInPeru():undefined} min={type==='number'?'0.01':undefined} step={type==='number'?'0.01':undefined} value={form[key]} onChange={event=>setForm(current=>({...current,[key]:event.target.value}))} className="mt-2 w-full rounded-lg border border-slate-200 p-3"/></label>)}</fieldset><div className="flex flex-wrap gap-3"><button disabled={busy} className="aa-button aa-button-primary">{busy?'Guardando…':'Confirmar datos del anuncio'}</button>{editId&&<button type="button" onClick={()=>{setEditId(null);setForm({...empty});}} className="aa-button aa-button-secondary">Cancelar</button>}</div></form></details>}</section>;
}
