"use client";
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { propertyDisplayId } from '@/lib/property-display-id';
import { todayInPeru } from '@/lib/calendar.mjs';
type Task={id:number;codigo:string;nombre:string;posicion:number|null;tipo:string|null;propietarioNombres:string|null;propietarioApellidos:string|null;actividad:string;fechaLimite:string|null;responsable:string|null};
const labels:Record<string,string>={visita:'Registrar visita',tasacion:'Registrar precios',expediente:'Completar expediente',publicacion:'Confirmar publicación'};
const destinations:Record<string,string>={visita:'/registrar-visitas',tasacion:'/registrar-tasaciones',expediente:'/tasaciones-textos-pendientes',publicacion:'/tasaciones-textos-pendientes'};
export default function WorkAgenda(){const [items,setItems]=useState<Task[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [reload,setReload]=useState(0);useEffect(()=>{const controller=new AbortController();fetch('/api/seguimiento',{cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();const data=await response.json();if(!controller.signal.aborted){setItems(data.items);setError('');}}).catch(()=>{if(!controller.signal.aborted)setError('No se pudo consultar la agenda.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[reload]);return <section className="aa-card p-5 sm:p-6"><h2 className="text-lg font-bold">Agenda de atención</h2><p className="mt-2 text-sm text-slate-600">Los próximos 20 pasos, ordenados por su fecha límite. </p>{loading?<p className="mt-3 text-sm">Cargando agenda…</p>:error?<p role="alert" className="mt-3 text-sm text-red-700">{error}<button type="button" onClick={()=>{setLoading(true);setReload(current=>current+1);}} className="ml-3 min-h-11 underline">Reintentar</button></p>:items.length?<ul className="mt-4 divide-y divide-slate-200">{items.map(item=><li key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="min-w-0"><p className="break-words text-sm font-bold">{item.nombre}</p><p className="mt-1 text-xs text-slate-600">{item.responsable?.trim() && <>{item.responsable} · </>}{propertyDisplayId(item)}</p><p className={`mt-2 text-xs font-semibold ${item.fechaLimite&&item.fechaLimite<todayInPeru()?'text-red-700':'text-slate-700'}`}>{item.fechaLimite&&item.fechaLimite<todayInPeru()?'Vencido · ':''}Fecha límite: {item.fechaLimite??'Sin definir'}</p></div><Link href={`${destinations[item.actividad]}?inmueble=${item.id}${item.actividad==='expediente'?'#material':item.actividad==='publicacion'?'#listos':''}`} className="aa-button aa-button-secondary">{labels[item.actividad]} →</Link></li>)}</ul>:<p className="mt-4 text-sm text-emerald-800">No hay próximos pasos pendientes en la cartera consultada.</p>}</section>;}
