import Link from "next/link";

const inmuebles=[
 {n:"01",tipo:"Casa",nombre:"Casa Urbanización Buenos Aires",estado:"Activo",etapa:"Listo para publicar",ubicacion:"Nuevo Chimbote"},
 {n:"27",tipo:"Departamento",nombre:"Departamento Los Pinos",estado:"Activo",etapa:"Publicado",ubicacion:"Chimbote"},
 {n:"39",tipo:"Terreno",nombre:"Terreno Plaza 28 de Julio",estado:"Activo",etapa:"Tasación pendiente",ubicacion:"Chimbote"},
 {n:"45",tipo:"Terreno",nombre:"Terreno La Campiña",estado:"Activo",etapa:"Tasación pendiente",ubicacion:"Nuevo Chimbote"},
 {n:"54",tipo:"Terreno",nombre:"Terreno Los Pinos",estado:"Activo",etapa:"Visita pendiente",ubicacion:"Chimbote"},
];
export default function CarteraPage(){return <main className="min-h-screen bg-slate-50 p-6 lg:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Fase 1</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Cartera de inmuebles</h1><p className="mt-2 text-sm text-slate-500">Consulta y organiza toda la cartera, incluyendo activos e históricos.</p></div><Link href="/registrar-inmueble" className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">+ Registrar inmueble</Link></div><div className="mt-6 grid gap-3 md:grid-cols-4"><select className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-600"><option>Todos los estados</option><option>Activos</option><option>Históricos</option><option>No activos</option></select><select className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-600"><option>Todas las etapas</option><option>Visita pendiente</option><option>Tasación pendiente</option><option>Publicado</option></select><select className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-600"><option>Tipo de inmueble</option><option>Casa</option><option>Departamento</option><option>Terreno</option></select><input placeholder="Buscar inmueble..." className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none placeholder:text-slate-400 focus:border-slate-400"/></div><section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><p className="font-bold text-slate-900">Posiciones activas</p><p className="mt-1 text-xs text-slate-500">42 ocupadas · 48 disponibles de una capacidad de 90.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Pos.</th><th className="px-5 py-3">Inmueble</th><th className="px-5 py-3">Ubicación</th><th className="px-5 py-3">Etapa</th><th className="px-5 py-3">Estado</th></tr></thead><tbody className="divide-y divide-slate-100">{inmuebles.map(x=><tr key={x.n} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold text-slate-700">{x.n}</td><td className="px-5 py-4"><p className="text-sm font-semibold text-slate-800">{x.nombre}</p><p className="mt-1 text-xs text-slate-400">{x.tipo}</p></td><td className="px-5 py-4 text-sm text-slate-600">{x.ubicacion}</td><td className="px-5 py-4"><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-semibold text-amber-700">{x.etapa}</span></td><td className="px-5 py-4 text-xs font-semibold text-emerald-700">{x.estado}</td></tr>)}</tbody></table></div></section></main>